/**
 * POST-EXPORT — writes out/.htaccess for Hostinger (Apache / LiteSpeed).
 *
 * Without cache headers, PageSpeed flags "Serve static assets with an
 * efficient cache policy" and you lose several points for free. Hashed build
 * assets are immutable and can be cached for a year; HTML must revalidate so
 * content edits go live immediately.
 */
import { writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

if (!existsSync('out')) {
  console.error('[export] ./out not found — run `npm run build` first');
  process.exit(1);
}

/**
 * 301s for renamed article slugs. The admin panel appends to
 * content/redirects.json whenever a published article's slug changes, so the
 * old URL keeps its links and rankings instead of turning into a 404.
 */
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
let redirects = [];
if (existsSync('content/redirects.json')) {
  redirects = JSON.parse(await readFile('content/redirects.json', 'utf8')).filter(
    (r) => SLUG.test(r.from) && SLUG.test(r.to) && r.from !== r.to,
  );
}
const redirectRules = redirects
  .map((r) => `  RewriteRule ^blog/${r.from}/?$ /blog/${r.to}/ [R=301,L]`)
  .join('\n');

const htaccess = `# Generated by scripts/post-export.mjs — do not edit by hand

Options -MultiViews
ErrorDocument 404 /404.html
DirectoryIndex index.html index.php

# Hostinger deploys this folder from Git, so a .git directory sits beside the
# site. Never serve it (or any other dotfile other than the ACME challenge).
RedirectMatch 404 ^/\\.(?!well-known/)

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/css text/javascript \\
    application/javascript application/json application/xml image/svg+xml
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\\.(js|css|woff2)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.(avif|webp|jpg|jpeg|png|svg|ico)$">
    Header set Cache-Control "public, max-age=2592000"
  </FilesMatch>
  <FilesMatch "\\.(html|xml|txt)$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>
  Header set X-Content-Type-Options "nosniff"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

<IfModule mod_mime.c>
  AddType image/avif .avif
  AddType image/webp .webp
  AddType font/woff2 .woff2
</IfModule>

# Force HTTPS and strip www so the served URL matches the canonical exactly.
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteCond %{HTTP_HOST} !^(localhost|127\\.0\\.0\\.1)(:\\d+)?$
  RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]
  RewriteRule ^(.*)$ https://%1/$1 [R=301,L]
${redirectRules ? `\n  # Renamed articles (content/redirects.json)\n${redirectRules}\n` : ''}</IfModule>
`;

await writeFile('out/.htaccess', htaccess);
console.log(`[export] out/.htaccess written (${redirects.length} article redirect(s))`);
